name: Build LaTeX document
on: [ push ] # Trigger(s) du workflow, ici push uniquement
jobs:
  build_latex: # Name of the job
    runs-on: ubuntu-latest # type de machine sur laquelle les steps vont être exécutés
    steps:
      - name: Install Lualatex # Name of the step
        # Commande à exécuter pour installer les dépendances, Ghostscript et le reste des paquets sont nécessaires pour la compilation du Latex
        run: sudo apt install texlive-luatex texlive-latex-base texlive-latex-recommended texlive-pictures texlive-latex-extra fonts-ebgaramond ghostscript
      - name: Checkout the code of the repository
        uses: actions/checkout@v4 # Utilisation d'une action pour récupérer le code du repository
      - name: Build PDF
        run: /usr/bin/bash compile-latex.sh # Execution du script de compilation du PDF
      - name: Ghostscript compress PDF # Lossless compression of the PDF
        run: /usr/bin/bash compress-pdf.sh # Execution du script de compression du PDF
      - name: Upload compressed PDF
        uses: actions/upload-artifact@v4 # Utilisation d'une action pour uploader un artefact
        with:
          name: gs-compressed-pdf # Nom de l'artefact
          path: doc/build/pdf/Tests-Logiciels-Master-MS2D-gs-default.pdf # Chemin de des artefacts à stocker
