name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing customer_database.py pylint
        if: always()
        run: |
          pylint customer_database.py
      - name: Analysing witness_number.py pylint
        if: always()
        run: |
          pylint witness_number.py